/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CallBtn: typeof import('./src/components/call/CallPanel/CallBtn.vue')['default']
    CallPanel: typeof import('./src/components/call/CallPanel/CallPanel.vue')['default']
    CallPlayer: typeof import('./src/components/call/CallPlayer.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ExternalLink: typeof import('./src/components/ExternalLink.vue')['default']
    HangupBtn: typeof import('./src/components/call/CallPanel/HangupBtn.vue')['default']
    HomePanel: typeof import('./src/components/HomePanel.vue')['default']
    IconArrowLeftBold: typeof import('./src/components/icons/IconArrowLeftBold.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    IconExit: typeof import('./src/components/icons/IconExit.vue')['default']
    LoginPanel: typeof import('./src/components/LoginPanel.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
