# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TUICallingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TXAppBasic', :path => "../TXAppBasic/"
  pod 'TUICore', :path => "../../TUICore"
  pod 'TXLiteAVSDK_TRTC'
  pod 'Toast-Swift'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'TUICalling', :path => "../", :subspecs => ["TRTC"]
end
