# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TUICallKitApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'TXAppBasic', :path => "./TXAppBasic/"
  pod 'Toast-Swift'
  pod 'Alamofire'
  pod 'Kingfisher', '<= 6.3.1'
  pod 'SnapKit'
  pod 'TUICallKit', :path => "../", :subspecs => ["TRTC"]
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
